env:
  global:
    - CC_TEST_REPORTER_ID=d7a488e04dcb46fd9cdbd1fed94be310e17014e39f48ee2eb4b06c54df72feaf

language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2

sudo: false

addons:
  code_climate:
    repo_token: d7a488e04dcb46fd9cdbd1fed94be310e17014e39f48ee2eb4b06c54df72feaf

install:
    - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
