language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1

sudo: false

addons:
  code_climate:
    repo_token: d7a488e04dcb46fd9cdbd1fed94be310e17014e39f48ee2eb4b06c54df72feaf

install:
    - composer install

script: phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml

after_success:
- vendor/bin/test-reporter
